### ISSUE TITLE
Function suggestion: withFrozen

### ISSUE THREAD

**Issue by tejon** [cchalmers/pcg-random#3]
The pure System.Random interface is nice, but still considerably slower than working within the pcg-random idiom. Chasing an alternative, I've come up with this:

    withFrozen :: (Variate a)
               => (forall s. Gen s -> ST s a) -> FrozenGen -> (a, FrozenGen)
    withFrozen f g = runST $ flip runStateT g $ do
      gen <- get >>= \frozen -> restore frozen
      x <- lift $ f gen
      save gen >>= \frozen -> put frozen
      return x

By way of example, I've also got a function

    roll :: (PrimMonad m) => Int -> Gen (PrimState m) -> m Int

and it works with either `withFrozen (roll n) g` or `withSystemRandom $ roll n`.

I'm sketchy on the order of arguments -- I also had the idea of working this into a StateT variant, but putting the function last would be more convenient in a lot of cases -- and make no guarantees as to my code being anywhere close to optimal, but it does work and it's MUCH faster than the System.Random interface.

**Comment by cchalmers** [comment]
Yeah, the `System.Random` interface is unfortunately very slow because of how the class is defined. There's a [GSOC project](https://www.google-melange.com/gsoc/project/details/google/gsoc2015/nkartashov/5634387206995968) that will hopefully fix this.

There's no need for `StateT` here, it's simply:

```{.haskell}
withFrozen :: (forall s. Gen s -> ST s a) -> FrozenGen -> (a, FrozenGen)
withFrozen f s = runST $ do
  g  <- restore s
  a  <- f g
  s' <- save g
  return (a, s')
```

or even

```{.haskell}
withFrozen f s = runST $ restore s >>= \g -> liftA2 (,) (f g) (save g)
```

which I'll add.

I've actually started a pure branch [here](https://github.com/cchalmers/pcg-random/blob/pure/src/System/Random/PCG/Fast/Pure.hs) which performs faster than using `ST`. I couldn't figure out a nice interface and since I only use the `ST` version I've just left it until the GSOC project comes.

**Comment by cchalmers** [comment]
Added in aa5b4829db7d3668abdfccc9a9bc9834436aad82. I decided to flip the arguments.

**Comment by tejon** [comment]
My predictions of suboptimality have yet to come up short. ;) Ed Kmett brought up GSOC yesterday on #haskell-game too, sounds like there's real momentum there.
